export const Icons = {
  Logo: require('../assets/images/logo.png'),
  Logo_color: require('../assets/images/logo-color.png'),
  bgImage: require('../assets/images/forgetpw-bg.png'),
  lg_bgImage: require('../assets/images/login-bg.jpg'),
  logo_gg: require('../assets/images/google-logo.png'),
  su_bgImage: require('../assets/images/signup-bg.jpg'),
  ex_headerBgImg: require('../assets/images/explore-bg.png'),
  emptyPostImg: require('../assets/images/empty-post.png'),
  searchPending: require('../assets/images/ic-search-pending.png'),

  ic_mapIcon: require('../assets/images/ic-map.png'),

  ic_explore: require('../assets/images/ic-explore.png'),
  ic_explore_active: require('../assets/images/ic-explore-active.png'),
  ic_newfeed: require('../assets/images/ic-newsfeed.png'),
  ic_newfeed_active: require('../assets/images/ic-newsfeed-active.png'),
  ic_message: require('../assets/images/ic-message.png'),
  ic_message_active: require('../assets/images/ic-message-active.png'),
  ic_mypage: require('../assets/images/ic-mypage.png'),
  ic_mypage_active: require('../assets/images/ic-mypage-active.png'),
  ic_manage: require('../assets/images/ic-manage.png'),
  ic_manage_active: require('../assets/images/ic-manage-active.png'),

  ic_send: require('../assets/images/ic-send.png'),

  ic_alipaySrc: require('../assets/images/cc-icons/alipay.png'),
  ic_amexSrc: require('../assets/images/cc-icons/amex.png'),
  ic_dinersSrc: require('../assets/images/cc-icons/diners.png'),
  ic_discoverSrc: require('../assets/images/cc-icons/discover.png'),
  ic_eloSrc: require('../assets/images/cc-icons/elo.png'),
  ic_hiperSrc: require('../assets/images/cc-icons/hiper.png'),
  ic_hipercardSrc: require('../assets/images/cc-icons/hipercard.png'),
  ic_jcbSrc: require('../assets/images/cc-icons/jcb.png'),
  ic_maestroSrc: require('../assets/images/cc-icons/maestro.png'),
  ic_mastercardSrc: require('../assets/images/cc-icons/mastercard.png'),
  ic_mirSrc: require('../assets/images/cc-icons/mir.png'),
  ic_paypalSrc: require('../assets/images/cc-icons/paypal.png'),
  ic_unionpaySrc: require('../assets/images/cc-icons/unionpay.png'),
  ic_visaSrc: require('../assets/images/cc-icons/visa.png'),
  ic_chatIc: require('../assets/images/noti-icons/chat.png'),
  ic_congratulationsReward: require('../assets/images/ic-badges/congratulations-reward.jpg'),
  ic_hangoutIc: require('../assets/images/noti-icons/hangout.png'),

  ic_notificationIc: require('../assets/images/noti-icons/notification.png'),
  ic_rateIc: require('../assets/images/noti-icons/rate.png'),
  ic_reactIc: require('../assets/images/noti-icons/react.png'),
  ic_relationIc: require('../assets/images/noti-icons/relation.png'),
  ic_hangout: require('../assets/images/ic-hangout.png'),

  ic_twitter: require('../assets/images/twitter.png'),
};
